# Namespace to deploy the helm chart
namespace: honestcard

# Name of deployment to restart
deploymentNameToRestart: cms-card-repayment-ingestion

# Cron schedule for restarting the deployment
cronSchedule: '0 * * * *'
