apiVersion: batch/v1
kind: CronJob
metadata:
  name: deployment-restart
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: {{ .Values.cronSchedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 # timeout, makes most sense with 
                                 # "waiting for rollout" variant specified below
      template:
        metadata:
          annotations:
          {{- toYaml .Values.annotations | nindent 12 }}     
        spec:
          serviceAccountName: deployment-restart 
          restartPolicy: Never
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest@sha256:08afc880eea24f36572644ccae85fb3e573a6ff1b7161135a3ae9a5eab222df2 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/{{ .Values.deploymentNameToRestart }}'