apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deployment-restart
  namespace: {{ .Values.namespace }}
spec:
  concurrencyPolicy: Forbid
  schedule: '*/5 * * * *' # cron spec of time, here, 8 o'clock
  jobTemplate:
    spec:
      backoffLimit: 2 
      activeDeadlineSeconds: 600 # timeout, makes most sense with 
                                 # "waiting for rollout" variant specified below
      template:
        spec:
          serviceAccountName: deployment-restart 
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl 
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - 'deployment/{{ .Values.deploymentNameToRestart }}'