apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-restart
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    resourceNames: [ {{ .Values.deploymentName }} ]
    verbs: ["get", "patch", "list", "watch"] 